const grammar = {
    "?": { grammar: "?", text: "/help的替代命令，提供命令使用帮助" },
    ability: { grammar: "ability", text: "赋予或剥夺玩家的能力" },
    advancement: { grammar: "advancement", text: "添加、移除或查询玩家的进度" },
    agent: { grammar: "agent", text: "操控吉祥物" },
    alwaysday: { grammar: "alwaysday", text: "/daylock的替代命令，锁定或解锁日夜循环" },
    attribute: { grammar: "attribute", text: "修改或查询玩家和生物的属性" },
    ban: { grammar: "ban <selector>", text: "将玩家加入封禁列表" },
    "ban-ip": { grammar: "ban-ip", text: "将IP地址加入封禁列表" },
    banlist: { grammar: "banlist", text: "显示封禁列表" },
    bossbar: { grammar: "bossbar", text: "修改或查询Boss栏" },
    camerashake: { grammar: "camerashake", text: "启用镜头抖动效果" },
    changesetting: { grammar: "changesetting", text: "更改一个正在运行的服务器的设置" },
    classroommode: { grammar: "classroommode", text: "允许编辑受限制的方块" },
    clear: { grammar: "clear <selector>", text: "从玩家物品栏中删除物品" },
    clearspawnpoint: { grammar: "clearspawnpoint", text: "从世界中移除出生点" },
    clone: { grammar: "clone", text: "将特定区域的方块复制到另一处" },
    closechat: { grammar: "closechat", text: "如果聊天框已打开，则关闭它" },
    closewebsocket: { grammar: "closewebsocket", text: "断开已连接的WebSocket服务器" },
    code: { grammar: "code", text: "启动代码编辑器" },
    codebuilder: { grammar: "codebuilder", text: "设置一个玩家的代码编辑状态" },
    connect: { grammar: "connect", text: "/wsserver的替代命令，连接至一个WebSocket服务器" },
    data: { grammar: "data", text: "允许玩家获取、合并或是移除实体或方块的数据标签" },
    datapack: { grammar: "datapack", text: "控制加载的数据包" },
    daylock: { grammar: "daylock", text: "/alwaysday的替代命令，锁定或解锁日夜循环" },
    debug: { grammar: "debug", text: "开始或结束调试会话" },
    defaultgamemode: { grammar: "defaultgamemode", text: "更改默认的游戏模式" },
    dedicatedwsserver: { grammar: "dedicatedwsserver", text: "尝试连接一个WebSocket服务器" },
    deop: { grammar: "deop <selector>", text: "撤销玩家的管理员权限" },
    dialogue: { grammar: "dialogue", text: "打开一个玩家的NPC对话" },
    difficulty: { grammar: "difficulty", text: "设置难度等级" },
    effect: { grammar: "effect <selector>", text: "添加或移除状态效果" },
    enableencryption: { grammar: "enableencryption", text: "为当前WebSocket连接启用加密" },
    enchant: { grammar: "enchant", text: "附魔玩家的物品" },
    event: { grammar: "event", text: "用于触发一个实体的事件" },
    execute: { grammar: "execute", text: "代表实体执行另一命令" },
    experience: { grammar: "experience", text: "/xp的替代命令，给予玩家经验" },
    fill: { grammar: "fill", text: "在某个区域填充特定方块" },
    fog: { grammar: "fog", text: "用于更改玩家当前的雾设置" },
    forceload: { grammar: "forceload", text: "强制不断加载区块" },
    function: { grammar: "function", text: "运行一个函数" },
    gamemode: { grammar: "gamemode", text: "更改玩家的游戏模式" },
    gamerule: { grammar: "gamerule", text: "更改或查询游戏规则" },
    getchunkdata: { grammar: "getchunkdata", text: "获得特定区块的数据" },
    getchunks: { grammar: "getchunks", text: "获得已加载区块列表" },
    geteduclientinfo: { grammar: "geteduclientinfo", text: "显示有关客户端的数据" },
    geteduserverinfo: { grammar: "geteduserverinfo", text: "显示有关服务端的数据" },
    getlocalplayername: { grammar: "getlocalplayername", text: "显示本地玩家姓名" },
    getspawnpoint: { grammar: "getspawnpoint", text: "获得特定玩家的出生地点" },
    gettopsolidblock: { grammar: "gettopsolidblock", text: "获得特定位置以下最高的非空气方块" },
    give: { grammar: "give <selector> <item> 数量-整数", text: "给予玩家物品" },
    globalpause: { grammar: "globalpause", text: "查询或设置所有玩家的世界暂停状态" },
    help: { grammar: "help", text: "/?的替代命令，提供命令使用帮助" },
    immutableworld: { grammar: "immutableworld", text: "设置世界的不可变状态" },
    item: { grammar: "item", text: "用于修改方块或实体的物品栏" },
    kick: { grammar: "kick <selector>", text: "将玩家踢出服务器" },
    kill: { grammar: "kill <selector>", text: "清除实体（玩家、生物、掉落物等）" },
    lesson: { grammar: "lesson", text: "处理教育版课程报告" },
    list: { grammar: "list", text: "列出服务器中的玩家" },
    listd: { grammar: "listd", text: "以JSON形式列出服务器中的玩家及信息" },
    locate: { grammar: "locate <structure>", text: "显示最近的给定结构的坐标" },
    locatebiome: { grammar: "locatebiome", text: "显示最近的给定生物群系的坐标" },
    loot: { grammar: "loot", text: "从一个物品栏中掉落物品到地面上" },
    me: { grammar: "me", text: "显示一条关于自己的信息" },
    mixer: { grammar: "mixer", text: "Mixer交互性控制" },
    mobevent: { grammar: "mobevent", text: "控制或查询允许运行的生物事件" },
    msg: { grammar: "msg", text: "/tell和/w的替代命令，向另一玩家发送私信" },
    music: { grammar: "music", text: "设置玩家是否能控制当前播放的音乐" },
    op: { grammar: "op <selector>", text: "授予玩家管理员权限" },
    ops: { grammar: "ops", text: "/permission的替代命令，重载并应用权限" },
    pardon: { grammar: "pardon <selector>", text: "从封禁列表中移除玩家封禁项目" },
    "pardon-ip": { grammar: "pardon-ip", text: "从封禁列表中移除IP封禁项目" },
    particle: { grammar: "particle <particles>", text: "创建粒子" },
    permission: { grammar: "permission", text: "/ops的替代命令，重载并应用权限" },
    playanimation: { grammar: "playanimation", text: "运行一次特定动作" },
    playsound: { grammar: "playsound", text: "播放音效" },
    publish: { grammar: "publish", text: "向局域网开放单人游戏世界" },
    querytarget: { grammar: "querytarget", text: "检测某实体所在坐标、旋转角度、所在维度及专用ID" },
    recipe: { grammar: "recipe", text: "给予或剥夺合成配方" },
    reload: { grammar: "reload", text: "从硬盘中重新加载战利品表、进度和函数" },
    remove: { grammar: "remove", text: "移除吉祥物" },
    replaceitem: { grammar: "replaceitem", text: "替换物品栏中的物品" },
    ride: { grammar: "ride", text: "控制一个实体的骑行状态" },
    save: { grammar: "save", text: "准备备份，查询其状态或恢复" },
    "save-all": { grammar: "save-all", text: "保存服务器世界状态到硬盘" },
    "save-off": { grammar: "save-off", text: "关闭服务器自动保存" },
    "save-on": { grammar: "save-on", text: "开启服务器自动保存" },
    say: { grammar: "say", text: "向多个玩家发送消息" },
    schedule: { grammar: "schedule", text: "安排函数在特定的游戏刻后运行" },
    scoreboard: {
        grammar: () => {
            let value = valueSplitArray().split(",");
            switch (value[1]) {
                case "players":
                    switch (value[2]) {
                        case "list":
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [list:'列出所有被记分板系统追踪的实体'|reset:'清空实体目标的一项或所有分数'|test:'检测计分项是否在最小值和最大值范围内（若不填，默认最大值为整型数最大值2147483647'|random:'把实体目标在计分项上的分数设为一个从最小值到最大值的随机数，包含最大最小值'|set:'设置实体目标在记分项记分项上的分数'|add:'往实体目标在记分项记分项上的分数增加分数'|remove:'从实体目标在记分项记分项上的分数扣除分数'|operation:'使用选择器在记分项记分项上的分数作为输入，进行运算操作后把结果作为记分项实体目标在记分项名为目标记分项上的分数'] [\*:'所有正在被记分板追踪的实体'|@p:'距离最近的玩家'|@r:'随机玩家'|@a:'所有玩家'|@e:'所有实体'|@s:'命令的执行者'|@c:'自己的吉祥物'|@v:'所有吉祥物']";
                        case "reset":
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [list:'列出所有被记分板系统追踪的实体'|reset:'清空实体目标的一项或所有分数'|test:'检测计分项是否在最小值和最大值范围内（若不填，默认最大值为整型数最大值2147483647'|random:'把实体目标在计分项上的分数设为一个从最小值到最大值的随机数，包含最大最小值'|set:'设置实体目标在记分项记分项上的分数'|add:'往实体目标在记分项记分项上的分数增加分数'|remove:'从实体目标在记分项记分项上的分数扣除分数'|operation:'使用选择器在记分项记分项上的分数作为输入，进行运算操作后把结果作为记分项实体目标在记分项名为目标记分项上的分数'] [\*:'所有正在被记分板追踪的实体'|@p:'距离最近的玩家'|@r:'随机玩家'|@a:'所有玩家'|@e:'所有实体'|@s:'命令的执行者'|@c:'自己的吉祥物'|@v:'所有吉祥物'] 记分项：字符串";
                        case "test":
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [list:'列出所有被记分板系统追踪的实体'|reset:'清空实体目标的一项或所有分数'|test:'检测计分项是否在最小值和最大值范围内（若不填，默认最大值为整型数最大值2147483647'|random:'把实体目标在计分项上的分数设为一个从最小值到最大值的随机数，包含最大最小值'|set:'设置实体目标在记分项记分项上的分数'|add:'往实体目标在记分项记分项上的分数增加分数'|remove:'从实体目标在记分项记分项上的分数扣除分数'|operation:'使用选择器在记分项记分项上的分数作为输入，进行运算操作后把结果作为记分项实体目标在记分项名为目标记分项上的分数'] [\*:'所有正在被记分板追踪的实体'|@p:'距离最近的玩家'|@r:'随机玩家'|@a:'所有玩家'|@e:'所有实体'|@s:'命令的执行者'|@c:'自己的吉祥物'|@v:'所有吉祥物'] 记分项：字符串 最小值：整数（可为\*） 最大值：整数（不填默认为\*）";
                        case "random":
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [list:'列出所有被记分板系统追踪的实体'|reset:'清空实体目标的一项或所有分数'|test:'检测计分项是否在最小值和最大值范围内（若不填，默认最大值为整型数最大值2147483647'|random:'把实体目标在计分项上的分数设为一个从最小值到最大值的随机数，包含最大最小值'|set:'设置实体目标在记分项记分项上的分数'|add:'往实体目标在记分项记分项上的分数增加分数'|remove:'从实体目标在记分项记分项上的分数扣除分数'|operation:'使用选择器在记分项记分项上的分数作为输入，进行运算操作后把结果作为记分项实体目标在记分项名为目标记分项上的分数'] [\*:'所有正在被记分板追踪的实体'|@p:'距离最近的玩家'|@r:'随机玩家'|@a:'所有玩家'|@e:'所有实体'|@s:'命令的执行者'|@c:'自己的吉祥物'|@v:'所有吉祥物'] 记分项：字符串 最小值：整数（可为\*） 最大值：整数（不填默认为\*）";
                        case "set":
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [list:'列出所有被记分板系统追踪的实体'|reset:'清空实体目标的一项或所有分数'|test:'检测计分项是否在最小值和最大值范围内（若不填，默认最大值为整型数最大值2147483647'|random:'把实体目标在计分项上的分数设为一个从最小值到最大值的随机数，包含最大最小值'|set:'设置实体目标在记分项记分项上的分数'|add:'往实体目标在记分项记分项上的分数增加分数'|remove:'从实体目标在记分项记分项上的分数扣除分数'|operation:'使用选择器在记分项记分项上的分数作为输入，进行运算操作后把结果作为记分项实体目标在记分项名为目标记分项上的分数'] [\*:'所有正在被记分板追踪的实体'|@p:'距离最近的玩家'|@r:'随机玩家'|@a:'所有玩家'|@e:'所有实体'|@s:'命令的执行者'|@c:'自己的吉祥物'|@v:'所有吉祥物'] 记分项：字符串 数量：整数";
                        case "add":
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [list:'列出所有被记分板系统追踪的实体'|reset:'清空实体目标的一项或所有分数'|test:'检测计分项是否在最小值和最大值范围内（若不填，默认最大值为整型数最大值2147483647'|random:'把实体目标在计分项上的分数设为一个从最小值到最大值的随机数，包含最大最小值'|set:'设置实体目标在记分项记分项上的分数'|add:'往实体目标在记分项记分项上的分数增加分数'|remove:'从实体目标在记分项记分项上的分数扣除分数'|operation:'使用选择器在记分项记分项上的分数作为输入，进行运算操作后把结果作为记分项实体目标在记分项名为目标记分项上的分数'] [\*:'所有正在被记分板追踪的实体'|@p:'距离最近的玩家'|@r:'随机玩家'|@a:'所有玩家'|@e:'所有实体'|@s:'命令的执行者'|@c:'自己的吉祥物'|@v:'所有吉祥物'] 记分项：字符串 数量：整数";
                        case "remove":
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [list:'列出所有被记分板系统追踪的实体'|reset:'清空实体目标的一项或所有分数'|test:'检测计分项是否在最小值和最大值范围内（若不填，默认最大值为整型数最大值2147483647'|random:'把实体目标在计分项上的分数设为一个从最小值到最大值的随机数，包含最大最小值'|set:'设置实体目标在记分项记分项上的分数'|add:'往实体目标在记分项记分项上的分数增加分数'|remove:'从实体目标在记分项记分项上的分数扣除分数'|operation:'使用选择器在记分项记分项上的分数作为输入，进行运算操作后把结果作为记分项实体目标在记分项名为目标记分项上的分数'] [\*:'所有正在被记分板追踪的实体'|@p:'距离最近的玩家'|@r:'随机玩家'|@a:'所有玩家'|@e:'所有实体'|@s:'命令的执行者'|@c:'自己的吉祥物'|@v:'所有吉祥物'] 记分项：字符串 数量：整数";
                        case "operation":
                                    return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [list:'列出所有被记分板系统追踪的实体'|reset:'清空实体目标的一项或所有分数'|test:'检测计分项是否在最小值和最大值范围内（若不填，默认最大值为整型数最大值2147483647'|random:'把实体目标在计分项上的分数设为一个从最小值到最大值的随机数，包含最大最小值'|set:'设置实体目标在记分项记分项上的分数'|add:'往实体目标在记分项记分项上的分数增加分数'|remove:'从实体目标在记分项记分项上的分数扣除分数'|operation:'使用选择器在记分项记分项上的分数作为输入，进行运算操作后把结果作为记分项实体目标在记分项名为目标记分项上的分数'] [\*:'所有正在被记分板追踪的实体'|@p:'距离最近的玩家'|@r:'随机玩家'|@a:'所有玩家'|@e:'所有实体'|@s:'命令的执行者'|@c:'自己的吉祥物'|@v:'所有吉祥物'] 目标记分项：字符串 [+=:'求和'|-=:'求差'|\*=:'求积'|/=:'求商'|%=:'求余'|=:'赋值'|<:'取较小值'|>:'取较大值'|><:'交换选择器与目标名称的分数'] [\*:'所有正在被记分板追踪的实体'|@p:'距离最近的玩家'|@r:'随机玩家'|@a:'所有玩家'|@e:'所有实体'|@s:'命令的执行者'|@c:'自己的吉祥物'|@v:'所有吉祥物'] 记分项：字符串";
                        default:
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [list:'列出所有被记分板系统追踪的实体'|reset:'清空实体目标的一项或所有分数'|test:'检测计分项是否在最小值和最大值范围内（若不填，默认最大值为整型数最大值2147483647'|random:'把实体目标在计分项上的分数设为一个从最小值到最大值的随机数，包含最大最小值'|set:'设置实体目标在记分项记分项上的分数'|add:'往实体目标在记分项记分项上的分数增加分数'|remove:'从实体目标在记分项记分项上的分数扣除分数'|operation:'使用选择器在记分项记分项上的分数作为输入，进行运算操作后把结果作为记分项实体目标在记分项名为目标记分项上的分数']";
                    }
                case "objectives":
                    switch (value[2]) {
                        case "add":
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [add:'创建一个具有给定的名称、准则、可选的显示名称的记分项'|list:'列出所有存在的记分项、显示名称与准则'|remove:'删除记分板系统中该记分项的所有有关内容'|setdisplay:'在指定位置显示指定记分项的分数信息'] 记分项:字符串 [dummy:'纯数字准则'] 显示名称";
                        case "list":
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [add:'创建一个具有给定的名称、准则、可选的显示名称的记分项'|list:'列出所有存在的记分项、显示名称与准则'|remove:'删除记分板系统中该记分项的所有有关内容'|setdisplay:'在指定位置显示指定记分项的分数信息']";
                        case "setdisplay":
                            switch (value[3]) {
                                case "list":
                                    return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [add:'创建一个具有给定的名称、准则、可选的显示名称的记分项'|list:'列出所有存在的记分项、显示名称与准则'|remove:'删除记分板系统中该记分项的所有有关内容'|setdisplay:'在指定位置显示指定记分项的分数信息'] [list:'玩家列表'|sidebar:'侧边栏'|belowname:'名字下方'] 记分项：字符串 [ascending:'升序'|descending:'降序']";
                                case "sidebar":
                                    return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [add:'创建一个具有给定的名称、准则、可选的显示名称的记分项'|list:'列出所有存在的记分项、显示名称与准则'|remove:'删除记分板系统中该记分项的所有有关内容'|setdisplay:'在指定位置显示指定记分项的分数信息'] [list:'玩家列表'|sidebar:'侧边栏'|belowname:'名字下方'] 记分项：字符串 [ascending:'升序'|descending:'降序']";
                                case "belowname":
                                    return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [add:'创建一个具有给定的名称、准则、可选的显示名称的记分项'|list:'列出所有存在的记分项、显示名称与准则'|remove:'删除记分板系统中该记分项的所有有关内容'|setdisplay:'在指定位置显示指定记分项的分数信息'] [list:'玩家列表'|sidebar:'侧边栏'|belowname:'名字下方'] 记分项：字符串";
                                default:
                                    return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [add:'创建一个具有给定的名称、准则、可选的显示名称的记分项'|list:'列出所有存在的记分项、显示名称与准则'|remove:'删除记分板系统中该记分项的所有有关内容'|setdisplay:'在指定位置显示指定记分项的分数信息'] [list:'玩家列表'|sidebar:'侧边栏'|belowname:'名字下方']";
                            }
                        case "remove":
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [add:'创建一个具有给定的名称、准则、可选的显示名称的记分项'|list:'列出所有存在的记分项、显示名称与准则'|remove:'删除记分板系统中该记分项的所有有关内容'|setdisplay:'在指定位置显示指定记分项的分数信息'] 记分项：字符串";
                        default:
                            return "scoreboard [players:'记分目标选项'|objectives:'记分板选项'] [add:'创建一个具有给定的名称、准则、可选的显示名称的记分项'|list:'列出所有存在的记分项、显示名称与准则'|remove:'删除记分板系统中该记分项的所有有关内容'|setdisplay:'在指定位置显示指定记分项的分数信息']";
                    }
                default:
                    return "scoreboard [players:'记分项选项'|objectives:'记分板选项']";
            }
            // if (value[1] === "players") {
            // } else return "scoreboard [players:'记分目标选项'|objectives:'记分板选项']"
        },
        text: "管理记分板的目标、玩家和队伍",
    },
    seed: { grammar: "seed", text: "显示世界种子" },
    setblock: { grammar: "setblock", text: "将方块替换为其他方块" },
    setidletimeout: { grammar: "setidletimeout", text: "设置无操作玩家被踢出的延时" },
    setmaxplayers: { grammar: "setmaxplayers", text: "设置可加入游戏的玩家数量上限" },
    setworldspawn: { grammar: "setworldspawn", text: "设置世界出生点" },
    spawnitem: { grammar: "spawnitem", text: "在特定位置生成一个物品实体" },
    spawnpoint: { grammar: "spawnpoint", text: "设置一个玩家的出生地点" },
    spectate: { grammar: "spectate", text: "使一个处于旁观模式的玩家旁观一个实体" },
    spreadplayers: { grammar: "spreadplayers", text: "将实体传送到随机位置" },
    stop: { grammar: "stop", text: "关闭服务器" },
    stopsound: { grammar: "stopsound", text: "停止音效" },
    structure: { grammar: "structure", text: "无需结构方块即可保存和加载结构" },
    summon: { grammar: "summon <summonable_entity>", text: "生成一个实体" },
    tag: { grammar: "tag <selector> [add:'添加标签'|remove:'移除标签'|list:'列出所有标签'] 名称", text: "修改实体的标签" },
    takepicture: { grammar: "takepicture", text: "从一个玩家的角度拍摄另一个玩家的照片" },
    team: { grammar: "team", text: "修改队伍" },
    teammsg: { grammar: "teammsg", text: "/tm的替代命令，指定要发送给队伍的消息" },
    teleport: { grammar: "teleport", text: "/tp的替代命令，传送实体" },
    tell: { grammar: "tell", text: "/msg和/w的替代命令，向另一个玩家发送私信" },
    tellraw: { grammar: "tellraw", text: "向玩家显示JSON消息" },
    testfor: { grammar: "testfor", text: "统计符合给定条件的实体" },
    testforblock: { grammar: "testforblock", text: "检测某方块是否在某位置" },
    testforblocks: { grammar: "testforblocks", text: "检测两个区域中的方块是否相同" },
    tickingarea: { grammar: "tickingarea", text: "添加、删除或列出常加载区域" },
    time: { grammar: "time", text: "更改或查询游戏中的世界时间" },
    title: { grammar: "title", text: "管理屏幕上的标题" },
    titleraw: { grammar: "titleraw", text: "使用JSON管理屏幕上的标题" },
    tm: { grammar: "tm", text: "/teammsg的替代命令，指定要发送给队伍的消息" },
    toggledownfall: { grammar: "toggledownfall", text: "切换天气" },
    tp: { grammar: "tp <selector>", text: "/teleport的替代命令，传送实体" },
    trigger: { grammar: "trigger", text: "设置一个触发器" },
    videostream: { grammar: "videostream", text: "连接一个WebSocket服务器，并进行视频推流" },
    w: { grammar: "w", text: "/tell和/msg的替代命令，向另一玩家发送私信" },
    wb: { grammar: "wb", text: "/worldbuilder的替代命令，给予能编辑受限制方块的能力" },
    weather: { grammar: "weather", text: "设置天气" },
    whitelist: { grammar: "whitelist", text: "管理服务器白名单" },
    worldborder: { grammar: "worldborder", text: "管理世界边界" },
    worldbuilder: { grammar: "worldbuilder", text: "/worldbuilder的替代命令，给予能编辑受限制方块的能力" },
    wsserver: { grammar: "wsserver", text: "/connect的替代命令，连接至WebSocket服务器" },
    xp: { grammar: "xp", text: "/experience的替代命令[仅Java版]，增加或减少一个玩家的经验" },
};
const variate = {
    selector: {
        "@p": "距离最近的玩家",
        "@r": "随机玩家",
        "@a": "所有玩家",
        "@e": "所有实体",
        "@s": "命令的执行者",
        "@c": "自己的吉祥物",
        "@v": "所有吉祥物",
    },
    particles: {
        "minecraft:arrow_spell_emitter": "药水箭粒子",
        "minecraft:balloon_gas_particle": "气球气体粒子",
        "minecraft:basic_bubble_particle": "基础气泡粒子（水中显示）",
        "minecraft:basic_bubble_particle_manual": "基础气泡粒子（水中显示）「落水」",
        "minecraft:basic_crit_particle": "基础暴击粒子（满弦弓）",
        "minecraft:basic_flame_particle": "基础火焰粒子",
        "minecraft:basic_portal_particle": "基础末影粒子",
        "minecraft:basic_smoke_particle": "基础烟雾粒子",
        "minecraft:bleach": "生气粒子",
        "minecraft:block_destruct": "方块破坏粒子（无法显示）",
        "minecraft:block_slide": "方块滑行粒子（无法显示）「疾跑脚底粒子？」",
        "minecraft:blue_flame_particle": "蓝色火焰粒子",
        "minecraft:breaking_item_icon": "破坏物品图标（无法显示）",
        "minecraft:breaking_item_terrain": "破坏物品地形（无法显示）",
        "minecraft:bubble_column_bubble": "气泡柱气泡（水中显示）",
        "minecraft:bubble_column_down_particle": "气泡柱下沉气泡（水中显示）",
        "minecraft:bubble_column_up_particle": "气泡柱上升气泡（水中显示）",
        "minecraft:camera_shoot_explosion": "照相机拍照粒子",
        "minecraft:campfire_smoke_particle": "篝火烟雾「低」",
        "minecraft:campfire_tall_smoke_particle": "篝火烟雾「高」",
        "minecraft:candle_flame_particle": "蜡烛火焰粒子",
        "minecraft:cauldron_bubble_particle": "炼药锅粒子效果（水中显示）",
        "minecraft:cauldron_explosion_emitter": "炼药锅爆炸",
        "minecraft:cauldron_spell_emitter": "炼药锅药水注入（无法显示）「药水填充炼药锅粒子」",
        "minecraft:cauldron_splash_particle": "炼药锅药水粒子飞溅(无法显示)「空瓶拿取炼药锅药水粒子」",
        "minecraft:colored_flame_particle": "彩色火焰粒子（黑色）",
        "minecraft:conduit_absorb_particle": "潮涌核心聚集粒子",
        "minecraft:conduit_attack_emitter": "潮涌核心攻击粒子",
        "minecraft:conduit_particle": "潮涌核心粒子",
        "minecraft:critical_hit_emitter": "暴击粒子（跳劈）",
        "minecraft:crop_growth_area_emitter": "作物生长区域粒子（显示条件未知）",
        "minecraft:crop_growth_emitter": "作物生长粒子（催熟）",
        "minecraft:death_explosion_emitter": "死亡粒子",
        "minecraft:dolphin_move_particle": "海豚游泳粒子（水中显示）",
        "minecraft:dragon_breath_fire": "龙息「球爆炸」",
        "minecraft:dragon_breath_lingering": "龙息萦绕（无法显示）「龙吐火」",
        "minecraft:dragon_breath_trail": "龙息踪迹（末影龙火球踪迹）",
        "minecraft:dragon_death_explosion_emitter": "末影龙死亡粒子",
        "minecraft:dragon_destroy_block": "末影龙破坏方块粒子",
        "minecraft:dragon_dying_explosion": "末影龙死亡爆炸",
        "minecraft:egg_destroy_emitter": "蛋破坏粒子",
        "minecraft:electric_spark_particle": "电火花粒子（显示条件未知,可能是教育版专属）",
        "minecraft:elephant_tooth_paste_vapor_particle": "大象牙膏蒸汽粒子",
        "minecraft:enchanting_table_particle": "附魔台粒子",
        "minecraft:end_chest": "末影箱粒子",
        "minecraft:endrod": "末地烛粒子",
        "minecraft:evocation_fang_particle": "恼鬼召唤粒子",
        "minecraft:evoker_spell": "唤魔粒子",
        "minecraft:explosion_manual": "爆炸粒子1",
        "minecraft:explosion_particle": "爆炸粒子2",
        "minecraft:eye_of_ender_bubble_particle": "末影之眼气泡粒子（水中显示）",
        "minecraft:eyeofender_death_explode_particle": "末影之眼炸裂粒子",
        "minecraft:falling_border_dust_particle": "边界方块坠落粒子",
        "minecraft:falling_dust": "灰尘坠落粒子1",
        "minecraft:falling_dust_concrete_powder_particle": "灰尘坠落粒子2（混凝土）",
        "minecraft:falling_dust_dragon_egg_particle": "灰尘坠落粒子3（龙蛋）",
        "minecraft:falling_dust_gravel_particle": "灰尘坠落粒子4（砂砾）",
        "minecraft:falling_dust_red_sand_particle": "灰尘坠落粒子5（红沙）",
        "minecraft:falling_dust_sand_particle": "灰尘坠落粒子6（沙子）",
        "minecraft:falling_dust_scaffolding_particle": "灰尘坠落粒子7（脚手架）",
        "minecraft:falling_dust_top_snow_particle": "灰尘坠落粒子8（顶层雪）",
        "minecraft:fish_hook_particle": "鱼钩下沉气泡（水中显示）",
        "minecraft:fish_pos_particle": "鱼的气泡（水中显示）",
        "minecraft:glow_particle": "发光粒子效果（无法显示）",
        "minecraft:guardian_attack_particle": "守卫者攻击粒子（水中显示）",
        "minecraft:guardian_water_move_particle": "守卫者水中移动粒子",
        "minecraft:heart_particle": "生命粒子",
        "minecraft:honey_drip_particle": "蜂蜜掉落粒子",
        "minecraft:huge_explosion_emitter": "大爆炸粒子1",
        "minecraft:huge_explosion_lab_misc_emitter": "大爆炸粒子2（实验室各种粒子）",
        "minecraft:ice_evaporation_emitter": "冰升华粒子",
        "minecraft:ink_emitter": "油墨粒子（显示方式未知）",
        "minecraft:knockback_roar_particle": "咆哮粒子",
        "minecraft:lab_table_heatblock_dust_particle": "实验室加热台灰尘颗粒",
        "minecraft:lab_table_misc_mystical_particle": "实验室表各种神秘粒子",
        "minecraft:large_explosion": "大爆炸分粒子",
        "minecraft:lava_drip_particle": "岩浆掉落粒子",
        "minecraft:lava_particle": "岩浆迸发粒子",
        "minecraft:llama_spit_smoke": "羊驼吐口水击中粒子",
        "minecraft:magnesium_salts_emitter": "镁盐发射器（镁条燃烧粒子?）",
        "minecraft:misc_fire_vapor_particle": "各种火蒸汽粒子（着火入水）",
        "minecraft:mob_block_spawn_emitter": "方块出生粒子",
        "minecraft:mob_portal": "下届门粒子",
        "minecraft:mobflame_emitter": "火柱（长时间存在）「过多会卡」",
        "minecraft:mobflame_single": "孤火",
        "minecraft:mobspell_emitter": "唤魔者召唤粒子",
        "minecraft:mycelium_dust_particle": "菌丝灰尘",
        "minecraft:nectar_drip_particle": "花蜜滴落（长时间存在）",
        "minecraft:note_particle": "音符",
        "minecraft:obsidian_glow_dust_particle": "发光黑曜石粒子",
        "minecraft:obsidian_tear_particle": "哭泣黑曜石粒子",
        "minecraft:phantom_trail_particle": "幻翼翅膀粒子（长时间存在，极易掉帧）",
        "minecraft:portal_directional": "定向末影粒子",
        "minecraft:portal_east_west": "东西末影粒子（显示方式未知）",
        "minecraft:portal_north_south": "南北末影粒子（显示方式未知）",
        "minecraft:portal_reverse_particle": "末影灰尘（正方形）",
        "minecraft:rain_splash_particle": "雨滴落粒子",
        "minecraft:redstone_ore_dust_particle": "红石矿粒子",
        "minecraft:redstone_repeater_dust_particle": "红石中继器粒子",
        "minecraft:redstone_torch_dust_particle": "红石火把粒子",
        "minecraft:redstone_wire_dust_particle": "红石线粒子",
        "minecraft:rising_border_dust_particle": "边界方块上升粒子",
        "minecraft:shulker_bullet": "潜赢贝子弹粒子",
        "minecraft:silverfish_grief_emitter": "蠹虫从石头出来粒子",
        "minecraft:snowflake_particle": "顶层雪粒子",
        "minecraft:soul_particle": "灵魂粒子",
        "minecraft:sparkler_emitter": "烟花粒子",
        "minecraft:splash_spell_emitter": "喷溅药水粒子",
        "minecraft:sponge_absorb_water_particle": "海绵吸水粒子（水中显示）",
        "minecraft:spore_blossom_ambient_particle": "孢子花环境粒子（显示条件未知）",
        "minecraft:spore_blossom_shower_particle": "孢子花开放粒子（显示条件未知）",
        "minecraft:squid_flee_particle": "乌贼逃跑粒子（水中显示）",
        "minecraft:squid_ink_bubble": "乌贼喷墨粒子（水中显示）",
        "minecraft:squid_move_particle": "乌贼移动粒子（水中显示）",
        "minecraft:stalactite_lava_drip_particle": "钟乳石滴岩浆",
        "minecraft:stalactite_water_drip_particle": "钟乳石滴水",
        "minecraft:stunned_emitter": "发呆粒子效果（长时间存在）",
        "minecraft:totem_manual": "不死图腾激活（小）",
        "minecraft:totem_particle": "不死图腾激活（大）",
        "minecraft:underwater_torch_particle": "水下火把粒子（水中显示）",
        "minecraft:villager_angry": "村民生气",
        "minecraft:villager_happy": "村民开心",
        "minecraft:water_drip_particle": "水滴坠落粒子",
        "minecraft:water_evaporation_actor_emitter": "水蒸发动作粒子",
        "minecraft:water_evaporation_bucket_emitter": "水桶蒸发粒子",
        "minecraft:water_evaporation_manual": "水蒸发粒子",
        "minecraft:water_splash_particle": "水溅出粒子1",
        "minecraft:water_splash_particle_manual": "水溅出粒子2",
        "minecraft:water_wake_particle": "漂水粒子",
        "minecraft:wax_particle": "蜡烛粒子",
        "minecraft:wither_boss_invulnerable": "凋零光环",
    },
    item: {
        acacia_boat: "金合欢木船",
        acacia_button: "金合欢木按钮",
        acacia_door: "金合欢木门",
        acacia_fence_gate: "金合欢木栅栏门",
        acacia_pressure_plate: "金合欢木压力板",
        acacia_sign: "金合欢木告示牌",
        acacia_stairs: "金合欢木楼梯",
        acacia_trapdoor: "金合欢木活板门",
        activator_rail: "激活铁轨",
        air: "空气",
        allow: "允许方块",
        amethyst_block: "紫水晶块",
        amethyst_cluster: "紫水晶簇",
        amethyst_shard: "紫水晶碎片",
        ancient_debris: "远古残骸",
        andesite_stairs: "安山岩楼梯",
        anvil: "铁砧",
        apple: "苹果",
        armor_stand: "盔甲架",
        arrow: "箭",
        axolotl_bucket: "",
        axolotl_spawn_egg: "美西螈刷怪蛋",
        azalea: "杜鹃花丛",
        azalea_leaves: "杜鹃树叶",
        azalea_leaves_flowered: "盛开的杜鹃树叶",
        baked_potato: "烤马铃薯",
        bamboo: "竹子",
        banner: "旗帜",
        barrel: "木桶",
        barrier: "屏障",
        basalt: "玄武岩",
        bat_spawn_egg: "蝙蝠刷怪蛋",
        beacon: "信标",
        bed: "床",
        bedrock: "基岩",
        bee_nest: "蜂巢",
        bee_spawn_egg: "蜜蜂刷怪蛋",
        beef: "生牛肉",
        beehive: "蜂箱",
        beetroot: "甜菜根",
        beetroot_seeds: "甜菜种子",
        beetroot_soup: "甜菜汤",
        bell: "钟",
        big_dripleaf: "大型垂滴叶",
        birch_boat: "白桦木船",
        birch_button: "白桦木按钮",
        birch_door: "白桦木门",
        birch_fence_gate: "白桦木栅栏门",
        birch_pressure_plate: "白桦木压力板",
        birch_sign: "白桦木告示牌",
        birch_stairs: "白桦木楼梯",
        birch_trapdoor: "白桦木活板门",
        black_candle: "黑色蜡烛",
        black_dye: "黑色染料",
        black_glazed_terracotta: "黑色带釉陶瓦",
        blackstone: "黑石",
        blackstone_slab: "黑石台阶",
        blackstone_stairs: "黑石楼梯",
        blackstone_wall: "黑石墙",
        blast_furnace: "高炉",
        blaze_powder: "烈焰粉",
        blaze_rod: "烈焰棒",
        blaze_spawn_egg: "烈焰人刷怪蛋",
        blue_candle: "蓝色蜡烛",
        blue_dye: "蓝色染料",
        blue_glazed_terracotta: "蓝色带釉陶瓦",
        blue_ice: "蓝冰",
        bone: "骨头",
        bone_block: "骨块",
        bone_meal: "骨粉",
        book: "书",
        bookshelf: "书架",
        border_block: "边界",
        bordure_indented_banner_pattern: "",
        bow: "弓",
        bowl: "碗",
        bread: "面包",
        brewing_stand: "酿造台",
        brick: "红砖",
        brick_block: "砖块",
        brick_stairs: "砖楼梯",
        brown_candle: "棕色蜡烛",
        brown_dye: "棕色染料",
        brown_glazed_terracotta: "棕色带釉陶瓦",
        brown_mushroom: "棕色蘑菇",
        brown_mushroom_block: "棕色蘑菇方块",
        bucket: "桶",
        budding_amethyst: "紫水晶母岩",
        cactus: "仙人掌",
        cake: "蛋糕",
        calcite: "方解石",
        campfire: "营火",
        candle: "蜡烛",
        carpet: "地毯",
        carrot: "胡萝卜",
        carrot_on_a_stick: "胡萝卜钓竿",
        cartography_table: "制图台",
        carved_pumpkin: "雕刻过的南瓜",
        cat_spawn_egg: "猫刷怪蛋",
        cauldron: "炼药锅",
        cave_spider_spawn_egg: "洞穴蜘蛛刷怪蛋",
        chain: "锁链",
        chain_command_block: "连锁型命令方块",
        chainmail_boots: "锁链靴子",
        chainmail_chestplate: "锁链胸甲",
        chainmail_helmet: "锁链头盔",
        chainmail_leggings: "锁链护腿",
        charcoal: "木炭",
        chest: "箱子",
        chest_minecart: "运输矿车",
        chicken: "生鸡肉",
        chicken_spawn_egg: "鸡刷怪蛋",
        chiseled_deepslate: "錾制深板岩",
        chiseled_nether_bricks: "錾制下界砖块",
        chiseled_polished_blackstone: "錾制磨制黑石",
        chorus_flower: "紫颂花",
        chorus_fruit: "紫颂果",
        chorus_plant: "紫颂植株",
        clay: "黏土块",
        clay_ball: "黏土球",
        clock: "时钟",
        coal: "煤炭",
        coal_block: "煤炭块",
        coal_ore: "煤矿石",
        cobbled_deepslate: "深板岩圆石",
        cobbled_deepslate_slab: "深板岩圆石台阶",
        cobbled_deepslate_stairs: "深板岩圆石楼梯",
        cobbled_deepslate_wall: "深板岩圆石墙",
        cobblestone: "圆石",
        cobblestone_wall: "圆石墙",
        cocoa_beans: "可可豆",
        cod: "生成鳕鱼",
        cod_bucket: "鳕鱼桶",
        cod_spawn_egg: "鳕鱼刷怪蛋",
        command_block: "命令方块",
        command_block_minecart: "命令方块矿车",
        comparator: "红石比较器",
        compass: "指南针",
        composter: "堆肥桶",
        concrete: "混凝土",
        concretepowder: "混凝土粉末",
        conduit: "潮涌核心",
        cooked_beef: "牛排",
        cooked_chicken: "熟鸡肉",
        cooked_cod: "熟鳕鱼",
        cooked_mutton: "熟羊肉",
        cooked_porkchop: "熟猪排",
        cooked_rabbit: "熟兔肉",
        cooked_salmon: "熟鲑鱼",
        cookie: "曲奇",
        copper_block: "铜块",
        copper_ingot: "铜锭",
        copper_ore: "铜矿石",
        coral: "珊瑚",
        coral_block: "珊瑚块",
        coral_fan: "珊瑚扇",
        coral_fan_dead: "失活的珊瑚扇",
        cow_spawn_egg: "牛刷怪蛋",
        cracked_deepslate_bricks: "裂纹深板岩砖",
        cracked_deepslate_tiles: "裂纹深板岩瓦",
        cracked_nether_bricks: "裂纹下界砖块",
        cracked_polished_blackstone_bricks: "裂纹磨制黑石砖",
        crafting_table: "工作台",
        creeper_banner_pattern: "",
        creeper_spawn_egg: "苦力怕刷怪蛋",
        crimson_button: "绯红木按钮",
        crimson_door: "绯红木门",
        crimson_fence: "绯红木栅栏",
        crimson_fence_gate: "绯红木栅栏门",
        crimson_fungus: "绯红菌",
        crimson_hyphae: "绯红菌核",
        crimson_nylium: "绯红菌岩",
        crimson_planks: "绯红木板",
        crimson_pressure_plate: "绯红木压力板",
        crimson_roots: "绯红菌索",
        crimson_sign: "绯红木告示牌",
        crimson_slab: "绯红木台阶",
        crimson_stairs: "绯红木楼梯",
        crimson_stem: "绯红菌柄",
        crimson_trapdoor: "绯红木活板门",
        crossbow: "弩",
        crying_obsidian: "哭泣的黑曜石",
        cut_copper: "切制铜块",
        cut_copper_slab: "切制铜台阶",
        cut_copper_stairs: "切制铜楼梯",
        cyan_candle: "青色蜡烛",
        cyan_dye: "青色染料",
        cyan_glazed_terracotta: "青色带釉陶瓦",
        dark_oak_boat: "深色橡木船",
        dark_oak_button: "深色橡木按钮",
        dark_oak_door: "深色橡木门",
        dark_oak_fence_gate: "深色橡木栅栏门",
        dark_oak_pressure_plate: "深色橡木压力板",
        dark_oak_sign: "深色橡木告示牌",
        dark_oak_stairs: "深色橡木楼梯",
        dark_oak_trapdoor: "深色橡木活板门",
        dark_prismarine_stairs: "暗海晶石楼梯",
        daylight_detector: "阳光探测器",
        deadbush: "枯萎的灌木",
        deepslate: "深板岩",
        deepslate_brick_slab: "深板岩砖台阶",
        deepslate_brick_stairs: "深板岩砖楼梯",
        deepslate_brick_wall: "深板岩砖墙",
        deepslate_bricks: "深板岩砖",
        deepslate_coal_ore: "深层煤矿石",
        deepslate_copper_ore: "深层铜矿石",
        deepslate_diamond_ore: "深层钻石矿石",
        deepslate_emerald_ore: "深层绿宝石矿石",
        deepslate_gold_ore: "深层金矿石",
        deepslate_iron_ore: "深层铁矿石",
        deepslate_lapis_ore: "深层青金石矿石",
        deepslate_redstone_ore: "深层红石矿石",
        deepslate_tile_slab: "深板岩瓦台阶",
        deepslate_tile_stairs: "深板岩瓦楼梯",
        deepslate_tile_wall: "深板岩瓦墙",
        deepslate_tiles: "深板岩瓦",
        deny: "拒绝方块",
        detector_rail: "探测铁轨",
        diamond: "钻石",
        diamond_axe: "钻石斧",
        diamond_block: "钻石块",
        diamond_boots: "钻石靴子",
        diamond_chestplate: "钻石胸甲",
        diamond_helmet: "钻石头盔",
        diamond_hoe: "钻石锄",
        diamond_horse_armor: "钻石马铠",
        diamond_leggings: "钻石护腿",
        diamond_ore: "钻石矿石",
        diamond_pickaxe: "钻石镐",
        diamond_shovel: "钻石锹",
        diamond_sword: "钻石剑",
        diorite_stairs: "闪长岩楼梯",
        dirt: "泥土/砂土",
        dirt_with_roots: "缠根泥土",
        dispenser: "发射器",
        dolphin_spawn_egg: "海豚刷怪蛋",
        donkey_spawn_egg: "驴刷怪蛋",
        double_plant: "向日葵/丁香/高草丛/大型蕨/玫瑰丛/牡丹",
        dragon_breath: "龙息",
        dragon_egg: "龙蛋",
        dried_kelp: "干海带",
        dried_kelp_block: "干海带块",
        dripstone_block: "滴水石块",
        dropper: "投掷器",
        drowned_spawn_egg: "溺尸刷怪蛋",
        egg: "鸡蛋",
        elder_guardian_spawn_egg: "远古守卫者刷怪蛋",
        elytra: "鞘翅",
        emerald: "绿宝石",
        emerald_block: "绿宝石块",
        emerald_ore: "绿宝石矿石",
        empty_map: "空地图",
        enchanted_book: "附魔书",
        enchanted_golden_apple: "附魔金苹果",
        enchanting_table: "附魔台",
        end_brick_stairs: "末地石砖楼梯",
        end_bricks: "末地石砖",
        end_crystal: "末影水晶",
        end_portal_frame: "末地传送门框架",
        end_rod: "末地烛",
        end_stone: "末地石",
        ender_chest: "末影箱",
        ender_eye: "末影之眼",
        ender_pearl: "末影珍珠",
        enderman_spawn_egg: "末影人刷怪蛋",
        endermite_spawn_egg: "末影螨刷怪蛋",
        evoker_spawn_egg: "唤魔者刷怪蛋",
        experience_bottle: "附魔之瓶",
        exposed_copper: "斑驳的铜块",
        exposed_cut_copper: "斑驳的切制铜块",
        exposed_cut_copper_slab: "斑驳的切制铜台阶",
        exposed_cut_copper_stairs: "斑驳的切制铜楼梯",
        farmland: "耕地",
        feather: "羽毛",
        fence: "橡木栅栏/云杉木栅栏/白桦木栅栏/丛林木栅栏/金合欢木栅栏/深色橡木栅栏",
        fence_gate: "橡木栅栏门",
        fermented_spider_eye: "发酵蛛眼",
        field_masoned_banner_pattern: "",
        filled_map: "地图",
        fire_charge: "火焰弹",
        firework_rocket: "烟花火箭",
        firework_star: "烟火之星",
        fishing_rod: "钓鱼竿",
        fletching_table: "制箭台",
        flint: "燧石",
        flint_and_steel: "打火石",
        flower_banner_pattern: "",
        flower_pot: "花盆",
        flowering_azalea: "盛开的杜鹃花丛",
        fox_spawn_egg: "狐狸刷怪蛋",
        frame: "物品展示框",
        frosted_ice: "霜冰",
        furnace: "熔炉",
        ghast_spawn_egg: "恶魂刷怪蛋",
        ghast_tear: "恶魂之泪",
        gilded_blackstone: "镶金黑石",
        glass: "玻璃",
        glass_bottle: "玻璃瓶",
        glass_pane: "玻璃板",
        glistering_melon_slice: "闪烁的西瓜片",
        glow_berries: "发光浆果",
        glow_frame: "荧光物品展示框",
        glow_ink_sac: "荧光墨囊",
        glow_lichen: "发光地衣",
        glow_squid_spawn_egg: "发光鱿鱼刷怪蛋",
        glowstone: "荧石",
        glowstone_dust: "荧石粉",
        goat_spawn_egg: "山羊刷怪蛋",
        gold_block: "金块",
        gold_ingot: "金锭",
        gold_nugget: "金粒",
        gold_ore: "金矿石",
        golden_apple: "金苹果",
        golden_axe: "金斧",
        golden_boots: "金靴子",
        golden_carrot: "金胡萝卜",
        golden_chestplate: "金胸甲",
        golden_helmet: "金头盔",
        golden_hoe: "金锄",
        golden_horse_armor: "金马铠",
        golden_leggings: "金护腿",
        golden_pickaxe: "金镐",
        golden_rail: "充能铁轨",
        golden_shovel: "金锹",
        golden_sword: "金剑",
        granite_stairs: "花岗岩楼梯",
        grass: "草",
        grass_path: "草径",
        gravel: "沙砾",
        gray_candle: "灰色蜡烛",
        gray_dye: "灰色染料",
        gray_glazed_terracotta: "灰色带釉陶瓦",
        green_candle: "绿色蜡烛",
        green_dye: "绿色染料",
        green_glazed_terracotta: "绿色带釉陶瓦",
        grindstone: "砂轮",
        guardian_spawn_egg: "守卫者刷怪蛋",
        gunpowder: "火药",
        hanging_roots: "垂根",
        hardened_clay: "陶瓦",
        hay_block: "干草块",
        heart_of_the_sea: "海洋之心",
        heavy_weighted_pressure_plate: "重质测重压力板",
        hoglin_spawn_egg: "疣猪兽刷怪蛋",
        honey_block: "蜂蜜块",
        honey_bottle: "蜂蜜瓶",
        honeycomb: "蜜脾",
        honeycomb_block: "蜜脾块",
        hopper: "漏斗",
        hopper_minecart: "漏斗矿车",
        horse_spawn_egg: "马刷怪蛋",
        husk_spawn_egg: "尸壳刷怪蛋",
        ice: "冰",
        infested_deepslate: "被虫蚀的深板岩",
        ink_sac: "墨囊",
        iron_axe: "铁斧",
        iron_bars: "铁栏杆",
        iron_block: "铁块",
        iron_boots: "铁靴子",
        iron_chestplate: "铁胸甲",
        iron_door: "铁门",
        iron_helmet: "铁头盔",
        iron_hoe: "铁锄",
        iron_horse_armor: "铁马铠",
        iron_ingot: "铁锭",
        iron_leggings: "铁护腿",
        iron_nugget: "铁粒",
        iron_ore: "铁矿石",
        iron_pickaxe: "铁镐",
        iron_shovel: "铁锹",
        iron_sword: "铁剑",
        iron_trapdoor: "铁活板门",
        jigsaw: "",
        jukebox: "唱片机",
        jungle_boat: "丛林木船",
        jungle_button: "丛林木按钮",
        jungle_door: "丛林木门",
        jungle_fence_gate: "丛林木栅栏门",
        jungle_pressure_plate: "丛林木压力板",
        jungle_sign: "丛林木告示牌",
        jungle_stairs: "丛林木楼梯",
        jungle_trapdoor: "丛林木活板门",
        kelp: "海带",
        ladder: "梯子",
        lantern: "灯笼",
        lapis_block: "青金石块",
        lapis_lazuli: "青金石",
        lapis_ore: "青金石矿石",
        large_amethyst_bud: "大型紫晶芽",
        lava_bucket: "熔岩桶",
        lead: "拴绳",
        leather: "皮革",
        leather_boots: "皮革靴子",
        leather_chestplate: "皮革胸甲",
        leather_helmet: "皮革帽子",
        leather_horse_armor: "皮革马铠",
        leather_leggings: "皮革裤子",
        leaves: "橡树树叶/云杉树叶/白桦树叶/丛林树叶",
        leaves2: "金合欢树叶/深色橡树树叶",
        lectern: "讲台",
        lever: "拉杆",
        light_block: "光源方块",
        light_blue_candle: "淡蓝色蜡烛",
        light_blue_dye: "淡蓝色染料",
        light_blue_glazed_terracotta: "淡蓝色带釉陶瓦",
        light_gray_candle: "淡灰色蜡烛",
        light_gray_dye: "淡灰色染料",
        light_weighted_pressure_plate: "轻质测重压力板",
        lightning_rod: "避雷针",
        lime_candle: "黄绿色蜡烛",
        lime_dye: "黄绿色染料",
        lime_glazed_terracotta: "黄绿色带釉陶瓦",
        lingering_potion: "滞留药水",
        lit_pumpkin: "南瓜灯",
        llama_spawn_egg: "羊驼刷怪蛋",
        lodestone: "磁石",
        lodestone_compass: "磁石指针",
        log: "橡木原木/云杉原木/白桦原木/丛林原木",
        log2: "金合欢原木/深色橡木原木",
        loom: "织布机",
        magenta_candle: "品红色蜡烛",
        magenta_dye: "品红色染料",
        magenta_glazed_terracotta: "品红色带釉陶瓦",
        magma: "岩浆块",
        magma_cream: "岩浆膏",
        magma_cube_spawn_egg: "岩浆怪刷怪蛋",
        medium_amethyst_bud: "中型紫晶芽",
        melon_block: "西瓜",
        melon_seeds: "西瓜种子",
        melon_slice: "西瓜片",
        milk_bucket: "奶桶",
        minecart: "矿车",
        mob_spawner: "刷怪笼",
        mojang_banner_pattern: "",
        monster_egg: "被虫蚀的石头/被虫蚀的圆石/被虫蚀的石砖/被虫蚀的苔石砖/被虫蚀的裂纹石砖/被虫蚀的錾制石砖",
        mooshroom_spawn_egg: "哞菇刷怪蛋",
        moss_block: "苔藓块",
        moss_carpet: "苔藓地毯",
        mossy_cobblestone: "苔石",
        mossy_cobblestone_stairs: "苔石楼梯",
        mossy_stone_brick_stairs: "苔石砖楼梯",
        mule_spawn_egg: "骡刷怪蛋",
        mushroom_stew: "蘑菇煲",
        music_disc_11: "音乐唱片",
        music_disc_13: "音乐唱片",
        music_disc_blocks: "音乐唱片",
        music_disc_cat: "音乐唱片",
        music_disc_chirp: "音乐唱片",
        music_disc_far: "音乐唱片",
        music_disc_mall: "音乐唱片",
        music_disc_mellohi: "音乐唱片",
        music_disc_pigstep: "音乐唱片",
        music_disc_stal: "音乐唱片",
        music_disc_strad: "音乐唱片",
        music_disc_wait: "音乐唱片",
        music_disc_ward: "音乐唱片",
        mutton: "熟羊肉/生羊肉",
        mycelium: "菌丝",
        name_tag: "命名牌",
        nautilus_shell: "鹦鹉螺壳",
        nether_brick: "下界砖",
        nether_brick_fence: "下界砖栅栏",
        nether_brick_stairs: "下界砖楼梯",
        nether_gold_ore: "下界金矿石",
        nether_sprouts: "下界苗",
        nether_star: "下界之星",
        nether_wart: "下界疣",
        nether_wart_block: "下界疣块",
        netherbrick: "下界砖",
        netherite_axe: "下界合金斧",
        netherite_block: "下界合金块",
        netherite_boots: "下界合金靴子",
        netherite_chestplate: "下界合金胸甲",
        netherite_helmet: "下界合金头盔",
        netherite_hoe: "下界合金锄",
        netherite_ingot: "下界合金锭",
        netherite_leggings: "下界合金护腿",
        netherite_pickaxe: "下界合金镐",
        netherite_scrap: "下界合金碎片",
        netherite_shovel: "下界合金锹",
        netherite_sword: "下界合金剑",
        netherrack: "下界岩",
        normal_stone_stairs: "石楼梯",
        noteblock: "音符盒",
        oak_boat: "橡木船",
        oak_sign: "橡木告示牌",
        oak_stairs: "橡木楼梯",
        observer: "侦测器",
        obsidian: "黑曜石",
        ocelot_spawn_egg: "豹猫刷怪蛋",
        orange_candle: "橙色蜡烛",
        orange_dye: "橙色染料",
        orange_glazed_terracotta: "橙色带釉陶瓦",
        oxidized_copper: "氧化的铜块",
        oxidized_cut_copper: "氧化的切制铜块",
        oxidized_cut_copper_slab: "氧化的切制铜台阶",
        oxidized_cut_copper_stairs: "氧化的切制铜楼梯",
        packed_ice: "浮冰",
        painting: "画",
        panda_spawn_egg: "熊猫刷怪蛋",
        paper: "纸",
        parrot_spawn_egg: "鹦鹉刷怪蛋",
        phantom_membrane: "幻翼膜",
        phantom_spawn_egg: "幻翼刷怪蛋",
        pig_spawn_egg: "猪刷怪蛋",
        piglin_banner_pattern: "",
        piglin_brute_spawn_egg: "猪灵蛮兵刷怪蛋",
        piglin_spawn_egg: "猪灵刷怪蛋",
        pillager_spawn_egg: "掠夺者刷怪蛋",
        pink_candle: "粉红色蜡烛",
        pink_dye: "粉红色染料",
        pink_glazed_terracotta: "粉红色带釉陶瓦",
        piston: "活塞",
        planks: "橡木木板/云杉木板/白桦木板/丛林木板/金合欢木板/深色橡木木板",
        podzol: "灰化土",
        pointed_dripstone: "滴水石锥",
        poisonous_potato: "毒马铃薯",
        polar_bear_spawn_egg: "北极熊刷怪蛋",
        polished_andesite_stairs: "磨制安山岩楼梯",
        polished_basalt: "磨制玄武岩",
        polished_blackstone: "磨制黑石",
        polished_blackstone_brick_slab: "磨制黑石砖台阶",
        polished_blackstone_brick_stairs: "磨制黑石砖楼梯",
        polished_blackstone_brick_wall: "磨制黑石砖墙",
        polished_blackstone_bricks: "磨制黑石砖",
        polished_blackstone_button: "磨制黑石按钮",
        polished_blackstone_pressure_plate: "磨制黑石压力板",
        polished_blackstone_slab: "磨制黑石台阶",
        polished_blackstone_stairs: "磨制黑石楼梯",
        polished_blackstone_wall: "磨制黑石墙",
        polished_deepslate: "磨制深板岩",
        polished_deepslate_slab: "磨制深板岩台阶",
        polished_deepslate_stairs: "磨制深板岩楼梯",
        polished_deepslate_wall: "磨制深板岩墙",
        polished_diorite_stairs: "磨制闪长岩楼梯",
        polished_granite_stairs: "磨制花岗岩楼梯",
        popped_chorus_fruit: "爆裂紫颂果",
        porkchop: "生猪排",
        potato: "马铃薯",
        potion: "药水",
        powder_snow_bucket: "细雪桶",
        prismarine: "海晶石/暗海晶石/海晶石砖",
        prismarine_bricks_stairs: "海晶石砖楼梯",
        prismarine_crystals: "海晶砂粒",
        prismarine_shard: "海晶碎片",
        prismarine_stairs: "海晶石楼梯",
        pufferfish: "河豚",
        pufferfish_bucket: "河豚桶",
        pufferfish_spawn_egg: "河豚刷怪蛋",
        pumpkin: "南瓜",
        pumpkin_pie: "南瓜派",
        pumpkin_seeds: "南瓜种子",
        purple_candle: "紫色蜡烛",
        purple_dye: "紫色染料",
        purple_glazed_terracotta: "紫色带釉陶瓦",
        purpur_block: "紫珀块/錾制紫珀块/紫珀柱/平滑紫珀块",
        purpur_stairs: "紫珀楼梯",
        quartz: "下界石英",
        quartz_block: "石英块/錾制石英块/石英柱/平滑石英块",
        quartz_bricks: "石英砖",
        quartz_ore: "下界石英矿石",
        quartz_stairs: "石英楼梯",
        rabbit: "生兔肉",
        rabbit_foot: "兔子脚",
        rabbit_hide: "兔子皮",
        rabbit_spawn_egg: "兔子刷怪蛋",
        rabbit_stew: "兔肉煲",
        rail: "铁轨",
        ravager_spawn_egg: "劫掠兽刷怪蛋",
        raw_copper: "粗铜",
        raw_copper_block: "粗铜块",
        raw_gold: "粗金",
        raw_gold_block: "粗金块",
        raw_iron: "粗铁",
        raw_iron_block: "粗铁块",
        red_candle: "红色蜡烛",
        red_dye: "红色染料",
        red_flower: "虞美人/兰花/绒球葱/蓝花美耳草/红色郁金香/橙色郁金香/白色郁金香/粉红色郁金香/滨菊/矢车菊/铃兰",
        red_glazed_terracotta: "红色带釉陶瓦",
        red_mushroom: "红色蘑菇",
        red_mushroom_block: "红色蘑菇方块",
        red_nether_brick: "红色下界砖块",
        red_nether_brick_stairs: "红色下界砖楼梯",
        red_sandstone: "红砂岩/錾制红砂岩/切制红砂岩/平滑红砂岩",
        red_sandstone_stairs: "红砂岩楼梯",
        redstone: "红石粉",
        redstone_block: "红石块",
        redstone_lamp: "红石灯",
        redstone_ore: "红石矿石",
        redstone_torch: "红石火把",
        repeater: "红石中继器",
        repeating_command_block: "循环型命令方块",
        respawn_anchor: "重生锚",
        rotten_flesh: "腐肉",
        saddle: "鞍",
        salmon: "生鲑鱼",
        salmon_bucket: "鲑鱼桶",
        salmon_spawn_egg: "鲑鱼刷怪蛋",
        sand: "沙子/红沙",
        sandstone: "砂岩/錾制砂岩/切制砂岩/平滑砂岩",
        sandstone_stairs: "砂岩楼梯",
        sapling: "橡树树苗/云杉树苗/白桦树苗/丛林树苗/金合欢树苗/深色橡树树苗",
        scaffolding: "脚手架",
        scute: "鳞甲",
        sea_pickle: "海泡菜",
        seagrass: "海草",
        sealantern: "海晶灯",
        shears: "剪刀",
        sheep_spawn_egg: "绵羊刷怪蛋",
        shield: "盾牌",
        shroomlight: "菌光体",
        shulker_box: "潜影盒",
        shulker_shell: "潜影壳",
        shulker_spawn_egg: "潜影贝刷怪蛋",
        silver_glazed_terracotta: "淡灰色带釉陶瓦",
        silverfish_spawn_egg: "蠹虫刷怪蛋",
        skeleton_horse_spawn_egg: "骷髅马刷怪蛋",
        skeleton_spawn_egg: "骷髅刷怪蛋",
        skull: "生物头颅",
        skull_banner_pattern: "",
        slime: "黏液块",
        slime_ball: "粘液球",
        slime_spawn_egg: "史莱姆刷怪蛋",
        small_amethyst_bud: "小型紫晶芽",
        small_dripleaf_block: "小型垂滴叶",
        smithing_table: "锻造台",
        smoker: "烟熏炉",
        smooth_basalt: "平滑玄武岩",
        smooth_quartz_stairs: "平滑石英楼梯",
        smooth_red_sandstone_stairs: "平滑红砂岩楼梯",
        smooth_sandstone_stairs: "平滑砂岩楼梯",
        smooth_stone: "平滑石头",
        snow: "雪块",
        snow_layer: "雪",
        snowball: "雪球",
        soul_campfire: "灵魂营火",
        soul_lantern: "灵魂灯笼",
        soul_sand: "灵魂沙",
        soul_soil: "灵魂土",
        soul_torch: "灵魂火把",
        spider_eye: "蜘蛛眼",
        spider_spawn_egg: "蜘蛛刷怪蛋",
        splash_potion: "喷溅药水",
        sponge: "海绵/湿海绵",
        spore_blossom: "孢子花",
        spruce_boat: "云杉木船",
        spruce_button: "云杉木按钮",
        spruce_door: "云杉木门",
        spruce_fence_gate: "云杉木栅栏门",
        spruce_pressure_plate: "云杉木压力板",
        spruce_sign: "云杉木告示牌",
        spruce_stairs: "云杉木楼梯",
        spruce_trapdoor: "云杉木活板门",
        spyglass: "望远镜",
        squid_spawn_egg: "鱿鱼刷怪蛋",
        stained_glass: "染色玻璃",
        stained_glass_pane: "染色玻璃板",
        stained_hardened_clay: "染色陶瓦",
        stick: "木棍",
        sticky_piston: "黏性活塞",
        stone: "石头",
        stone_axe: "石斧",
        stone_brick_stairs: "石砖楼梯",
        stone_button: "石质按钮",
        stone_hoe: "石锄",
        stone_pickaxe: "石镐",
        stone_pressure_plate: "石质压力板",
        stone_shovel: "石锹",
        stone_slab: "平滑石台阶/砂岩台阶/石化橡木台阶/圆石台阶/砖台阶/石砖台阶/石英台阶/下界砖台阶",
        stone_slab2: "红砂岩台阶/紫珀台阶/海晶石台阶/暗海晶石台阶/海晶石砖台阶/苔石台阶/平滑砂岩台阶/红色下界砖台阶",
        stone_slab3: "末地石砖台阶/平滑红砂岩台阶/磨制安山岩台阶/安山岩台阶/闪长岩台阶/磨制闪长岩台阶/花岗岩台阶/磨制花岗岩台阶",
        stone_slab4: "苔石砖台阶/平滑石英台阶/石台阶/切制砂岩台阶/切制红砂岩台阶",
        stone_stairs: "石楼梯",
        stone_sword: "石剑",
        stonebrick: "石砖/苔石砖/裂纹石砖/錾制石砖",
        stonecutter_block: "切石机",
        stray_spawn_egg: "流浪者刷怪蛋",
        strider_spawn_egg: "炽足兽刷怪蛋",
        string: "线",
        stripped_acacia_log: "去皮金合欢原木",
        stripped_birch_log: "去皮白桦原木",
        stripped_crimson_hyphae: "去皮绯红菌核",
        stripped_crimson_stem: "去皮绯红菌柄",
        stripped_dark_oak_log: "去皮深色橡木原木",
        stripped_jungle_log: "去皮丛林原木",
        stripped_oak_log: "去皮橡木原木",
        stripped_spruce_log: "去皮云杉原木",
        stripped_warped_hyphae: "去皮诡异菌核",
        stripped_warped_stem: "去皮诡异菌柄",
        structure_block: "结构方块",
        structure_void: "结构空位",
        sugar: "糖",
        sugar_cane: "甘蔗",
        suspicious_stew: "迷之炖菜",
        sweet_berries: "甜浆果",
        tallgrass: "蕨/草",
        target: "标靶",
        tinted_glass: "遮光玻璃",
        tnt: "TNT",
        tnt_minecart: "TNT 矿车",
        torch: "火把",
        totem_of_undying: "不死图腾",
        trapdoor: "活板门",
        trapped_chest: "陷阱箱",
        trident: "三叉戟",
        tripwire_hook: "绊线钩",
        tropical_fish: "热带鱼",
        tropical_fish_bucket: "热带鱼桶",
        tropical_fish_spawn_egg: "热带鱼刷怪蛋",
        tuff: "凝灰岩",
        turtle_egg: "海龟蛋",
        turtle_helmet: "海龟壳",
        turtle_spawn_egg: "海龟刷怪蛋",
        twisting_vines: "缠怨藤",
        undyed_shulker_box: "潜影盒",
        vex_spawn_egg: "恼鬼刷怪蛋",
        villager_spawn_egg: "村民刷怪蛋",
        vindicator_spawn_egg: "卫道士刷怪蛋",
        vine: "藤蔓",
        wandering_trader_spawn_egg: "流浪商人刷怪蛋",
        warped_button: "诡异木按钮",
        warped_door: "诡异木门",
        warped_fence: "诡异木栅栏",
        warped_fence_gate: "诡异木栅栏门",
        warped_fungus: "诡异菌",
        warped_fungus_on_a_stick: "诡异菌钓竿",
        warped_hyphae: "诡异菌核",
        warped_nylium: "诡异菌岩",
        warped_planks: "诡异木板",
        warped_pressure_plate: "诡异木压力板",
        warped_roots: "诡异菌索",
        warped_sign: "诡异木告示牌",
        warped_slab: "诡异木台阶",
        warped_stairs: "诡异木楼梯",
        warped_stem: "诡异菌柄",
        warped_trapdoor: "诡异木活板门",
        warped_wart_block: "诡异疣块",
        water_bucket: "水桶",
        waterlily: "睡莲",
        waxed_copper: "涂蜡铜块",
        waxed_cut_copper: "涂蜡切制铜块",
        waxed_cut_copper_slab: "涂蜡切制铜台阶",
        waxed_cut_copper_stairs: "涂蜡切制铜楼梯",
        waxed_exposed_copper: "斑驳的涂蜡铜块",
        waxed_exposed_cut_copper: "斑驳的涂蜡切制铜块",
        waxed_exposed_cut_copper_slab: "斑驳的涂蜡切制铜台阶",
        waxed_exposed_cut_copper_stairs: "斑驳的涂蜡切制铜楼梯",
        waxed_oxidized_copper: "氧化的涂蜡铜块",
        waxed_oxidized_cut_copper: "氧化的涂蜡切制铜块",
        waxed_oxidized_cut_copper_slab: "氧化的涂蜡切制铜台阶",
        waxed_oxidized_cut_copper_stairs: "氧化的涂蜡切制铜楼梯",
        waxed_weathered_copper: "锈蚀的涂蜡铜块",
        waxed_weathered_cut_copper: "锈蚀的涂蜡切制铜块",
        waxed_weathered_cut_copper_slab: "锈蚀的涂蜡切制铜台阶",
        waxed_weathered_cut_copper_stairs: "锈蚀的涂蜡切制铜楼梯",
        weathered_copper: "锈蚀的铜块",
        weathered_cut_copper: "锈蚀的切制铜块",
        weathered_cut_copper_slab: "锈蚀的切制铜台阶",
        weathered_cut_copper_stairs: "锈蚀的切制铜楼梯",
        web: "蜘蛛网",
        weeping_vines: "垂泪藤",
        wheat: "小麦",
        wheat_seeds: "小麦种子",
        white_candle: "白色蜡烛",
        white_dye: "白色染料",
        white_glazed_terracotta: "白色带釉陶瓦",
        witch_spawn_egg: "女巫刷怪蛋",
        wither_rose: "凋零玫瑰",
        wither_skeleton_spawn_egg: "凋灵骷髅刷怪蛋",
        wolf_spawn_egg: "狼刷怪蛋",
        wood: "橡木/云杉木/白桦木/丛林木/金合欢木/深色橡木/去皮橡木/去皮云杉木/去皮白桦木/去皮丛林木/去皮金合欢木/去皮深色橡木",
        wooden_axe: "木斧",
        wooden_button: "橡木按钮",
        wooden_door: "橡木门",
        wooden_hoe: "木锄",
        wooden_pickaxe: "木镐",
        wooden_pressure_plate: "橡木压力板",
        wooden_shovel: "木锹",
        wooden_slab: "橡木台阶/云杉木台阶/白桦木台阶/丛林木台阶/金合欢木台阶/深色橡木台阶",
        wooden_sword: "木剑",
        wool: "羊毛",
        writable_book: "书和羽毛笔",
        x: "这里是歆羽璇，这是一个彩蛋，玩的开心哈，如果到自己生日别忘了用give给自已一个蛋糕哦",
        yellow_candle: "黄色蜡烛",
        yellow_dye: "黄色染料",
        yellow_flower: "蒲公英",
        yellow_glazed_terracotta: "黄色带釉陶瓦",
        zoglin_spawn_egg: "僵尸疣猪兽刷怪蛋",
        zombie_horse_spawn_egg: "僵尸马刷怪蛋",
        zombie_pigman_spawn_egg: "僵尸猪人刷怪蛋",
        zombie_spawn_egg: "僵尸刷怪蛋",
        zombie_villager_spawn_egg: "僵尸村民刷怪蛋",
    },
    structure: {
        bastionremnant: "堡垒遗迹（猪灵堡垒）",
        buriedtreasure: "埋藏的宝藏",
        endcity: "末地城（在游戏尽头的城市）",
        fortress: "下届堡垒（阴森的要塞）",
        mansion: "林地府邸（dǐ）",
        mineshaft: "废弃矿井",
        monument: "海底遗迹",
        pillageroutpost: "掠夺者前哨",
        ruinedportal: "破坏的传送门",
        ruins: "水下遗迹",
        shipwreck: "沉船",
        stronghold: "要塞",
        temple: "神庙（沙漠神殿/丛林神庙/沼泽小屋/雪屋）",
        village: "村庄",
    },
    summonable_entity: {
        "minecraft:armor_stand": "盔甲架",
        "minecraft:arrow": "箭",
        "minecraft:axolotl": "美西螈",
        "minecraft:bat": "蝙蝠",
        "minecraft:bee": "蜜蜂",
        "minecraft:blaze": "烈焰人",
        "minecraft:boat": "船",
        "minecraft:cat": "猫",
        "minecraft:cave_spider": "洞穴蜘蛛",
        "minecraft:chest_minecart": "箱子矿车",
        "minecraft:chicken": "鸡",
        "minecraft:cod": "鳕鱼",
        "minecraft:command_block_minecart": "命令方块矿车",
        "minecraft:cow": "牛",
        "minecraft:creeper": "苦力怕",
        "minecraft:dolphin": "海豚",
        "minecraft:donkey": "驴",
        "minecraft:drowned": "溺尸",
        "minecraft:egg": "鸡蛋",
        "minecraft:elder_guardian": "远古守卫者",
        "minecraft:elder_guardian_ghost": "",
        "minecraft:ender_crystal": "末影水晶",
        "minecraft:ender_dragon": "末影龙",
        "minecraft:enderman": "末影人",
        "minecraft:endermite": "末影螨",
        "minecraft:evocation_fang": "唤魔者尖牙",
        "minecraft:evocation_illager": "唤魔者",
        "minecraft:fireworks_rocket": "烟花火箭",
        "minecraft:fox": "狐狸",
        "minecraft:ghast": "恶魂",
        "minecraft:glow_squid": "发光鱿鱼",
        "minecraft:goat": "山羊",
        "minecraft:guardian": "守卫者",
        "minecraft:hoglin": "疣猪兽",
        "minecraft:hopper_minecart": "漏斗矿车",
        "minecraft:horse": "马",
        "minecraft:husk": "尸壳",
        "minecraft:iron_golem": "铁傀儡",
        "minecraft:leash_knot": "拴绳结",
        "minecraft:lightning_bolt": "闪电",
        "minecraft:llama": "羊驼",
        "minecraft:magma_cube": "岩浆怪",
        "minecraft:minecart": "矿车",
        "minecraft:mooshroom": "哞菇",
        "minecraft:mule": "骡",
        "minecraft:npc": "NPC",
        "minecraft:ocelot": "豹猫",
        "minecraft:panda": "熊猫",
        "minecraft:parrot": "鹦鹉",
        "minecraft:phantom": "幻翼",
        "minecraft:pig": "猪",
        "minecraft:piglin": "猪灵",
        "minecraft:piglin_brute": "猪灵蛮兵",
        "minecraft:pillager": "掠夺者",
        "minecraft:polar_bear": "北极熊",
        "minecraft:pufferfish": "河豚",
        "minecraft:rabbit": "兔子",
        "minecraft:ravager": "劫掠兽",
        "minecraft:salmon": "鲑鱼",
        "minecraft:sheep": "绵羊",
        "minecraft:shulker": "潜影贝",
        "minecraft:silverfish": "蠹虫",
        "minecraft:skeleton": "骷髅",
        "minecraft:skeleton_horse": "骷髅马",
        "minecraft:slime": "史莱姆",
        "minecraft:snow_golem": "雪傀儡",
        "minecraft:snowball": "雪球",
        "minecraft:spider": "蜘蛛",
        "minecraft:splash_potion": "丢出的喷溅药水",
        "minecraft:squid": "鱿鱼",
        "minecraft:stray": "流浪者",
        "minecraft:strider": "炽足兽",
        "minecraft:tnt": "已激活的TNT",
        "minecraft:tnt_minecart": "TNT矿车",
        "minecraft:tropicalfish": "鱼钩",
        "minecraft:turtle": "海龟",
        "minecraft:vex": "恼鬼",
        "minecraft:villager": "村民",
        "minecraft:vindicator": "卫道士",
        "minecraft:wandering_trader": "流浪商人",
        "minecraft:witch": "女巫",
        "minecraft:wither": "凋灵",
        "minecraft:wither_skeleton": "凋灵骷髅",
        "minecraft:wolf": "狼",
        "minecraft:xp_bottle": "丢出经验瓶",
        "minecraft:xp_orb": "经验球",
        "minecraft:zoglin": "僵尸疣猪兽",
        "minecraft:zombie": "僵尸",
        "minecraft:zombie_horse": "僵尸马",
        "minecraft:zombie_pigman": "僵尸猪人",
        "minecraft:zombie_villager": "僵尸村民",
    },
};
